// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ARadio: typeof import('ant-design-vue/es')['Radio']
    ARadioGroup: typeof import('ant-design-vue/es')['RadioGroup']
    Index: typeof import('./src/components/ChatRoom/Index.vue')['default']
    JoinMessage: typeof import('./src/components/ChatRoom/Message/JoinMessage.vue')['default']
    MessageBox: typeof import('./src/components/ChatRoom/Message/MessageBox.vue')['default']
    MessageItem: typeof import('./src/components/ChatRoom/Message/MessageItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
